variable "config_file" {
  type = string
  default = "focal"
}

variable "ansible_playbook" {
  type    = string
  default = "myusersetup/playbook.yml"
}

variable "box_vagrantfile_template" {
  type    = string
  default = "Vagrantfile-linux-server.template"
}

variable "name" {
  type    = string
  default = "ubuntu-22.04-server-armd64"
}

variable "packer_images_output_dir" {
  type    = string
  default = "build"
}

variable "preseed_file_path" {
  type    = string
  default = "/ubuntu-server/preseed-ubuntu20.cfg"
}

variable "iso_url" {
  type    = string
  # Ubuntu for Mac M1
  default = "https://cdimage.ubuntu.com/releases/22.04/release/ubuntu-22.04.2-live-server-arm64.iso"
  #default = "http://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-live-server-amd64.iso"
}

variable "iso_checksum" {
  type    = string
  # Ubuntu for Mac M1
  default = "5e38b55d57d94ff029719342357325ed3bda38fa80054f9330dc789cd2d43931"
  #default = "http://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-live-server-amd64.iso"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "virtualbox-iso" "autogenerated_1" {
  #boot_command = [
  #      "<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><wait>",
  #      "<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><wait>",
  #      "<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><wait>",
  #      "<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><wait>",
  #      "<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><wait>",
  #      "<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><wait>",
  #      "<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><wait>",
  #      "<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><wait>",
  #      "<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><wait>",
  #      "<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><wait>",
  #      "c<wait5>",
  #      "etet gfxpayload=keep<enter><wait5>",
  #      "linux /casper/vmlinuz <wait5>",
  #      "autoinstall quiet mitigations=off fsck.mode=skip <wait5>",
  #      "net.ifnames=0 biosdevname=0 systemd.unified_cgroup_hierarchy=0 <wait5>",
  #      "ds=\"nocloud-net;s=http://{{.HTTPIP}}:{{.HTTPPort}}/\" <wait5>",
  #      "---<enter><wait5>",
  #      "initrd /casper/initrd<enter><wait5>",
  #      "boot<enter>"
  boot_command = [
    "<enter><wait><enter><f6><esc><wait> ",
    "autoinstall<wait>",
    " cloud-config-url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/http/jammy/user-data<wait>",
    " ds='nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/'",
    "<wait5><enter>"
  ]

  
  boot_wait            = "1s"
  iso_checksum         = var.iso_checksum
  iso_url              = var.iso_url
  guest_os_type        = "Ubuntu_64"
  shutdown_command     = "sudo shutdown -h now"

  cpus                 = "2"  
  disk_size            = "51200"
  memory               = "4096"
  gfx_controller       = "vmsvga"
  gfx_vram_size        = 128
  hard_drive_interface = "sata"
  headless             = "false"
  http_directory       = "http/jammy"
  ssh_password         = "ubuntu"
  ssh_timeout          = "60m"
  ssh_username         = "ubuntu"

  output_directory     = "${var.name}-virtualbox-iso"
  vm_name              = "${var.name}"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    execute_command = "echo 'vagrant' | {{ .Vars }} sudo -S -E bash -x '{{ .Path }}'"
    scripts         = ["scripts/ubuntu/update.sh", "scripts/ubuntu/disable_apt-daily.sh", "scripts/ubuntu/virtualbox-guest-x11.sh", "scripts/linux-common/add_vagrant_ssh_key.sh", "scripts/linux-common/cleanup.sh", "scripts/ubuntu/install_ansible.sh"]
  }

  post-processor "vagrant" {
    compression_level    = 9
    output               = "${var.packer_images_output_dir}/${var.name}-{{ .Provider }}.box"
    vagrantfile_template = "${var.box_vagrantfile_template}"
  }
}
